### ISSUE TITLE
怎么配置TPS_API和TPS_PUSH连接到本地的talk-os服务

### ISSUE THREAD

**Issue by dereksn** [jianliaoim/talk-android#1]
各位大牛，有问题想请教。我下载了talk-os和talk-android；默认设置启动talk-os，将talk-android中ApiConfig.java中的localhost替换为本地ip后，安装devBeta版本，一直提示“tps register failed”，不能收到别人发送的消息。配置如下（其中172.16.0.20是我开发机器的ip地址）

```
    ACCOUNT_URL = "http://172.16.0.20:7001/account/v1";
    REDIRECT_URI = "http://172.16.0.20:7001/account/union/callback/teambition";
    BASE_URL = "http://172.16.0.20:7001/v2";
    UPLOAD_URL = "http://172.16.0.20";
    AUTHOR_URL = "http://172.16.0.20:7001/account/union/teambition";
    POLICY_URL = "http://172.16.0.20:7001/site/items";
    CALL_URL = "http://172.16.0.20:8883";
    FORM_BASE_URL = "http://172.16.0.20:7001/v2/services/toapp?%s&_teamId=%s&url=%s";
    ABSENCE_URL = "http://172.16.0.20/forms/leave/new";
    SPIDER_URL = "http://172.16.0.20";
    SNAPPER_URL = "";
    AUTH_SERVICE_URL = "http://172.16.0.20";
    FEEDBACK_INTEGRATION_ID = "";
    TPS_API = "http://172.16.0.20:7001";
    TPS_PUSH = "ws://172.16.0.20:7001";
    //容联云需要的id,token,多人通话需要
    CALL_APP_ID = "";
    CALL_APP_TOKEN = "";
    CALL_ACCOUNT_SID = "";
    CALL_ACCOUNT_TOKEN = "";
```

**Comment by tiye** [comment]
@NLMartian ping

**Comment by podormeijia** [comment]
好像Server端没有/v1/users/register的API，拿不到SockectId

**Comment by sailxjx** [comment]
@wlanjie

**Comment by NLMartian** [comment]
貌似tps server端木有开源，可以改成Snapper来连接 @wlanjie

**Comment by wlanjie** [comment]
对的,server端没有这个api,所以拿不到socketid,我看下@NLMartian

**Comment by wlanjie** [comment]
@dereksn 这个得自己接socket,后端tps没有开放出来

**Comment by dereksn** [comment]
@NLMartian 是使用teambition/snapper-android吗？

**Comment by dereksn** [comment]
@NLMartian @wlanjie 
【问题1】因为没有/v1/users/register，我做了尝试，使用engine.io的客户端直接连接http://host:7001/snapper/socket，会收到一个socketId（替换/v1/users/register拿不到socketId的问题）；然后使用这个socketId，重新连接连接http://host:7001/snapper/socket?userId=socketId&deviceToken=XXXX，结果又在message事件中拿到一个socketId，而且与前面的不同。后面的请求使用第二次获取的socketId，这样对吗？
【问题2】后端的tps模块主要功能是什么？另外，我直接连通简聊后端的primus服务不就可以实现push了吗？我还需要开发后端的tps模块吗？
